<a href="https://colab.research.google.com/github/dahyun723/ESAA_1/blob/main/09_02_%ED%95%84%EC%82%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#넘파이
1. 넘파이 ndarray 개요
2. ndarray 데이터 타입
3. ndarray를 편리하게 생성하기 (arange, zeros, ones)
4. ndarray의 차원과 크기를 변경하는 reshape()
5. 넘파이의 ndarray의 데이터 세트 선택하기 (인덱싱 indexing)
6. 행렬의 정렬 sort(), argsort()
7. 선형대수 연산

넘파이 : 파이썬의 대표적인 패키지

넘파이를 이해하는 것은 파이썬 기반의 머신러닝에서 중요하다
-> 많은 머신러닝 알고리즘이 넘파이 기반으로 작성돼 있고, 이들 알고리즘의 입력 출력 데이터를 넘파이 배열타입으로 사용하기 때문에 중요

In [2]:
import numpy as np
#넘파이의 기반 데이터 타입은 ndarray이p다
#ndarray를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산을 수행한다
array1= np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)


In [ ]:
#넘파이의 array() 함수는 파이썬의 리스트같은 다양한 인자를 입력받아서 ndarray로 변환한다
#생성된 ndarray 배열의 shape 변수는 ndarray의 크기-> 튜플형태로 갖고 있음


In [3]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [5]:
# ndarray.ndim을 통해 각 array의 차원 확인

print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'. format(array1.ndim, array2.ndim, array3.ndim))


array1: 1차원, array2: 2차원, array3:  2차원


In [6]:
# dtype 속성으로 ndarrary 내의 데이터 타입 확인하기

list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [7]:
# int형과 string 형이 섞여 있는 리스트
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype) # 숫자형 값(int)가 문자열로 변환

# int형과 float 형이 섞여 있는 리스트
list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype) # int가 float으로 변환

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [8]:
# int32형 데이터를 float64로 변환
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

# float64를 int32로 변경
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

# float을 int형으로 변경할 때 소수점 이하는 당연히 모두 없어짐
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


#ndarray를 편리하게 생성하기

In [9]:
# 0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환

# arange() : 표준 함수 range()와 유사한 기능,
#0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터 값으로 변환
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [10]:
#zeros()
#튜플 형태의 shape 값을 입력하면
#모든 값을 0으로 채운 해당 shape를 가진 ndarray로 반환
zero_array = np.zeros((3,2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

#ones()
#튜플 형태의 shape 값을 입력하면
#모든 값을 1로 채운 해당 shape를 가진 ndarray를 반환
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [11]:
#reshape() : ndarray를 특정 차원 및 크기로 변환
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [12]:
array1.reshape(4,3)
#지정된 사이즈로 변경이 불가하면 오류가 발생

ValueError: cannot reshape array of size 10 into shape (4,3)

In [13]:

# 인자로 -1 적용

array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5) # 칼럼은 5로 고정, 로우를 자동으로 생성해 변환하라
print('array2 shape:', array2.shape) # 2x5

array3 = array1.reshape(5,-1) # 로우는 5로 고정, 칼럼을 자동으로 생성해 변환하라
print('array3 shape:', array3.shape) # 5x2


[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [14]:
# 변경할 수 없으면 에러 발생

array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

In [15]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


##인덱싱

In [16]:
# 1부터 9 까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)# 인덱스 -1은 맨 뒤의 데이터값

print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])
print('array1 :', array1)

# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))

array1 : [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [17]:
# 인덱스 -1은 맨 뒤의 데이터값

print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [18]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [19]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값;', array2d[0,0])
print('(row=0, col=1) index 가리키는 값;', array2d[0,1])
print('(row=1, col=0) index 가리키는 값;', array2d[1,0])
print('(row=2, col=2) index 가리키는 값;', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값; 1
(row=0, col=1) index 가리키는 값; 2
(row=1, col=0) index 가리키는 값; 4
(row=2, col=2) index 가리키는 값; 9


##슬라이싱
':' 기호를 이용해 연속한 데이터를 슬라이싱해서 추출, 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스 -1의 위치에 있는 데이터의 ndarray를 반환

':' 기호 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주

':' 기호 뒤에 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스로 간주

':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면 맨 처음/ 맨 마지막 인덱스로 간주

In [20]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [21]:
array1 = np.arange(start=1, stop = 10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [22]:
#2차원 ndarray 에서 슬라이싱
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2]\n', array2d[0:2,0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3,0:3])
print('array2d[1:3, :]\n', array2d[1:3,:])
print('array2d[:, :]\n', array2d[:,:])
print('array2d[:2, 1:]\n', array2d[:2,1:])
print('array2d[:2, 0]\n', array2d[:2,0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]


In [23]:
#2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환
print(array2d[0])
print(array2d[1])
print('array2d[0]:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0]: (3,) array2d[1] shape: (3,)


##팬시인덱싱
리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스의 해당하는 ndarray를 반환

In [24]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2] =>', array3.tolist())

array4 = array2d[[0,1],0:2]
print('array2d[[0,1],0:2] =>', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] =>', array5.tolist())

array2d[[0,1],2] => [3, 6]
array2d[[0,1],0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


##불린 인덱싱
조건 필터링과 검색을 동시에 할 수 있는 인덱스 방식

In [25]:
array1d = np.arange(start=1, stop=10)
# [] 안에 array1d > 5 Boolean indexing 을 적용
array3= array1d[array1d>5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [26]:
# 넘파이 ndarray 객체에 조건식을 할당하면

array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [28]:
# False 가 있는 인덱스는 무시함

boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [29]:
# 직접 인덱스 집합을 만들어 대입한 것과 동일

indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


##행렬의 정렬

In [30]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

#np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)

#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬 :', sort_array2)
print('org_array.sort() 호출 후 원본 행렬 :', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬 : None
org_array.sort() 호출 후 원본 행렬 : [1 3 5 9]


In [31]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [32]:
array2d = np.array([[8,12],
                    [7,1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬 : \n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬 : \n', sort_array2d_axis1)

로우 방향으로 정렬 : 
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬 : 
 [[ 8 12]
 [ 1  7]]


In [33]:
# np.argsort()를 이용해 원본 행렬의 정렬 시 행렬 인덱스 값 구하기

org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [34]:
# 내림차순으로 정렬 시에 원본 행렬의 인덱스를 구하기

org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [35]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스 : ', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스 :  [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


##전치행렬구하기

In [36]:
#행렬 내적(행렬 곱) - np.dot()을 이용
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
             [9,10],
             [11,12]])
dot_product = np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [37]:
#원 행렬에서 행과 열 위치를 교환한 우너소로 구성한 행렬 - transpose() 이용A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
